USR = {
  :about => "a",
  :weight => "b", # body
  :devices => "c", # computer
  :show_distance => "d",
  :ethnicity => "e",
  :favorites => "f",
  :groups => "g",
  :height => "h",
  :fb_id => "i",
  :location => "l",
  :messages => "m",
  :name => "n",
  :online_status => "o",
  :pic_id => "p",
  :headline => "q", # quote
  :last_online => "r", # recent
  :sex => "s",
  :updated => "t", # time
  :fb_username => "u",
  :likes => "v", # valentines
  :weblink => "w",
  :block => "x",
  :age => "y" # years
}
