USR = {
  :about => :a,
  :weight => :b, # body
  :devices => :c, # computer
  :show_distance => :d,
  :ethnicity => :e,
  :favorites => :f,
  :interests => :g,
  :height => :h,
  :fb_id => :i,
  :phone => :j, # j kinda looks like a phone
  :rel_stat => :k,
  :location => :l,
  :messages => :m,
  :name => :n,
  :online_status => :o,
  :pic_id => :p,
  :headline => :q, # quote
  :last_online => :r, # recent
  :sex => :s,
  :updated_date => :t, # time
  :fb_username => :u,
  :likes => :v, # valentines
  :website => :w,
  :block => :x,
  :birthday => :y, # years
  :show_birthday => :z
}
